### ISSUE TITLE
Composer usage

### ISSUE THREAD

**Issue by djmetla** [tebexio/TebexHeadless-OpenAPI#3]
Guys how to get  install PHP SDK via Composer? When i use `https://github.com/tebexio/TebexHeadless-OpenAPI.git` there is no composer json :/

**Comment by WildBamaBoy** [comment]
Hello, this repository is only for our OpenAPI schema and generated SDKs.

We have a separate PHP SDK that you can use with Composer located here: 

https://packagist.org/packages/tebex/tebex-sdk-php
https://github.com/tebexio/tebex-sdk-php
